*** Variables ***
${DOMAIN_URL}    %{DOMAIN_URL}
${POSTGRES_DB}    %{POSTGRES_DB}
${POSTGRES_USER}    %{POSTGRES_USER}
${POSTGRES_PASSWORD}    %{POSTGRES_PASSWORD}

${SITE_URL}     %{SITE_URL}
${MAIN_URL}     ${SITE_URL}/#/upload-file